[profile.default]
src = "contracts/src"
out = "contracts/out"
libs = ["contracts/lib"]
test = "contracts/test"
script = "contracts/script"
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = false
fuzz_runs = 256

[rpc_endpoints]
monad_testnet = "https://testnet-rpc.monad.xyz"

[etherscan]
monad_testnet = { key = "${MONAD_EXPLORER_API_KEY}", url = "https://testnet-explorer.monad.xyz/api" }
